AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MQTT Lambda with Tailscale

Resources:
  MqttNotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures: [x86_64]
      ImageUri: mqttnotifierfunction:latest
      Timeout: 60
      Environment:
        Variables:
          AWS_REGION: ""
          MQTT_BROKER_HOST: ""
          MQTT_TOPIC: ""
          MQTT_USERNAME_SECRET_ARN: ""
          MQTT_PASSWORD_SECRET_ARN: ""
          TAILSCALE_AUTH_KEY_SECRET_ARN: ""
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest
